services:
  redis:
    image: redis:7.4.1
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword}
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    


  front-end:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nextjs
    environment:
      - WEB_SERVER_URL=http://fastapi-server:8081
    ports:
      - "8079:8079"
    depends_on:
      - fastapi-server
    



  model-server:
    build: 
      context: ./modelserver
      dockerfile: Dockerfile.model
    ports:
      - "8000:8000"
    restart: on-failure
    


  fastapi-server:
    build: 
      context: ./middleware
      dockerfile: Dockerfile.fastapi
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
      - MODEL_SERVER_URL=http://model-server:8000
    ports:
      - "8081:8081"
    depends_on:
      - model-server
      - redis
    