FROM python:3.9
WORKDIR /home/code
COPY requirements.txt .
RUN pip install -r requirements.txt  && rm -rf /root/.cache/pip
COPY . .
EXPOSE 8000
CMD ["uvicorn", "model:app", "--host", "0.0.0.0", "--port", "8000"]