defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: nsgaii
  - override hydra/launcher: joblib
  - _self_

hydra:
  launcher:
    n_jobs: -1
  sweeper:
    sampler:
      seed: 123
    direction: [minimize, minimize]
    study_name: multi-objective
    storage: null
    n_trials: 20
    n_jobs: -1
    params:
      x: range(0, 15, step=0.5)
      y: choice(5,0,-.6)
      task: range(10,15)

# bool,choice,float,glob,int,interval,range,shuffle,sort,str,tag
# run without -m flag `sweeper` won't call
x: 1
y: 1
task: 1