apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-{{ .Values.configVersions.redis }}
  namespace: {{ .Values.namespace }}
data:
  hostname: redis-db-service
  port: "6379"


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: model-server-config-{{ .Values.configVersions.modelServer }}
  namespace: {{ .Values.namespace }}
data:
  model_server_url: http://model-server-service


--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config-{{ .Values.configVersions.webServer }}
  namespace: {{ .Values.namespace }}
data:
  web_server_url: http://fastapi-server-service