apiVersion: v1
kind: Secret
metadata:
  name: redis-secret-{{ .Values.configVersions.redis }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db_password: {{ .Values.redis.password | b64enc }}