apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  hostname: redis-db-service
  port: "6379"


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: model-server-config
data:
  model_server_url: http://model-server-service


--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  web_server_url: http://fastapi-server-service