# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend-server                          # this is used by ONLY Deployment no anywhere else
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-server
  template:
    metadata:
      labels:
        app: frontend-server
    spec:
      containers:
      - name: frontend-server
        image: frontend-server:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "900Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
            name: http
        env:
        - name: WEB_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: web_server_url


--- 
# Service

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend-server
  ports:
  - name: http
    port: 80
    targetPort: 80                  # must match containerPort from Deployment 


---

## Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: nextjs.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80 