FROM python:3.9
WORKDIR /home/code
COPY requirements.txt .
RUN pip install -r requirements.txt && rm -rf /root/.cache/pip
COPY . .
EXPOSE 8081
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8081"]  
# http://middle-ware only exepected from "FRONTEND"