services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        depends_on:
            - redis
    redis:
        image: redis:latest
        volumes:
            - redis-data:/data
volumes:
    redis-data: